# Generated by Django 4.2.30 on 2026-09-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0029_newsitem_live_rss_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('ai_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='connect.batches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='connect.courses')),
                ('source_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='connect.coursesession')),
            ],
            options={
                'db_table': 'challenge_question_pool',
            },
        ),
        migrations.CreateModel(
            name='StudentChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('completed_days', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_challenges', to='connect.batches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_challenges', to='connect.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='connect.students')),
            ],
            options={
                'db_table': 'student_challenges',
            },
        ),
        migrations.CreateModel(
            name='StudentChallengeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('challenge_date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='connect.studentchallenge')),
            ],
            options={
                'db_table': 'student_challenge_days',
            },
        ),
        migrations.CreateModel(
            name='StudentChallengeDayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('selected_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_questions', to='connect.studentchallengeday')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_day_questions', to='connect.challengequestionpool')),
            ],
            options={
                'db_table': 'student_challenge_day_questions',
                'ordering': ['question_order'],
                'indexes': [models.Index(fields=['challenge_day', 'question_order'], name='student_cha_challen_590ffe_idx'), models.Index(fields=['question'], name='student_cha_questio_6defd7_idx')],
                'unique_together': {('challenge_day', 'question'), ('challenge_day', 'question_order')},
            },
        ),
        migrations.AddIndex(
            model_name='studentchallengeday',
            index=models.Index(fields=['challenge', 'challenge_date'], name='student_cha_challen_a96f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentchallengeday',
            index=models.Index(fields=['challenge_date', 'status'], name='student_cha_challen_14091a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentchallengeday',
            unique_together={('challenge', 'challenge_date'), ('challenge', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='studentchallenge',
            index=models.Index(fields=['student', 'status'], name='student_cha_student_28b925_idx'),
        ),
        migrations.AddIndex(
            model_name='studentchallenge',
            index=models.Index(fields=['course', 'batch'], name='student_cha_course__fc6afc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentchallenge',
            index=models.Index(fields=['batch', 'status'], name='student_cha_batch_i_854fc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentchallenge',
            unique_together={('student', 'course', 'batch')},
        ),
        migrations.AddIndex(
            model_name='challengequestionpool',
            index=models.Index(fields=['course', 'batch', 'is_active'], name='challenge_q_course__11d658_idx'),
        ),
        migrations.AddIndex(
            model_name='challengequestionpool',
            index=models.Index(fields=['source_session', 'is_active'], name='challenge_q_source__b84264_idx'),
        ),
        migrations.AddIndex(
            model_name='challengequestionpool',
            index=models.Index(fields=['batch', 'difficulty', 'is_active'], name='challenge_q_batch_i_069e8b_idx'),
        ),
    ]
