# Generated by Django 4.2.30 on 2026-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0031_quick_challenge_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='actual_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='eligible_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
